# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\nmainserver\"=\n\x0b\x43hatMessage\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\x12\n\nsenderName\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\"\t\n\x07Nothing2\x87\x01\n\x0b\x43hatService\x12\x39\n\x07GetInfo\x12\x13.mainserver.Nothing\x1a\x17.mainserver.ChatMessage\"\x00\x12=\n\x0bSendMessage\x12\x17.mainserver.ChatMessage\x1a\x13.mainserver.Nothing\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHATMESSAGE']._serialized_start=26
  _globals['_CHATMESSAGE']._serialized_end=87
  _globals['_NOTHING']._serialized_start=89
  _globals['_NOTHING']._serialized_end=98
  _globals['_CHATSERVICE']._serialized_start=101
  _globals['_CHATSERVICE']._serialized_end=236
# @@protoc_insertion_point(module_scope)
