# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\nmainserver\"\x18\n\x08UserInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\")\n\x0eServerResponse\x12\x17\n\x0fgreetingMessage\x18\x01 \x01(\t2N\n\x0fGreetingService\x12;\n\x05Greet\x12\x14.mainserver.UserInfo\x1a\x1a.mainserver.ServerResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERINFO']._serialized_start=27
  _globals['_USERINFO']._serialized_end=51
  _globals['_SERVERRESPONSE']._serialized_start=53
  _globals['_SERVERRESPONSE']._serialized_end=94
  _globals['_GREETINGSERVICE']._serialized_start=96
  _globals['_GREETINGSERVICE']._serialized_end=174
# @@protoc_insertion_point(module_scope)
